title: Carmen Hove, PhD # your name (or website title) here
logo: "/images/PXL_20230709_191453021 (1).jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I'm an applied research scientist, with expertise in Bayesian modeling. 
  <br>
  <a href="https://www.linkedin.com/in/carmenhove/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-FKB9GWLFJ2 # your Google Analytics tracking ID here
