title: Carmen Hove, PhD # your name (or website title) here
logo: "/images/hiking.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  I'm an applied research scientist with expertise in using diverse datasets and advanced statistical modeling to investigate the causes and consequences of variation in immune function during different reproductive phases (e.g., pregnancy, menopause).
  <br><br>
  <a href="https://www.linkedin.com/in/carmenhove/">View My LinkedIn Profile</a> 
  <br><br>
  <a href="https://www.github.com/carmenhove/">View My GitHub</a> 
  <br><br>
  
remote_theme: pages-themes/minimal
google_analytics: G-FKB9GWLFJ2 # your Google Analytics tracking ID here
